#cloud-config

# Option 1 - Full installation using cURL
package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [ docker ]

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  # - unattended-upgrades

write_files:
- path: /etc/kind/2nodes-basic.yaml
  content: |
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
    - role: worker
    - role: worker
- path:  /etc/kind/metallb-config.yaml
  content: |
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: default-pool
      namespace: metallb-system
    spec:
      addresses:
      - 172.18.255.200-172.18.255.250
    ---
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: default
      namespace: metallb-system
    spec:
      ipAddressPools:
      - default-pool

runcmd:
  # install docker
  - mkdir -p /etc/apt/keyrings 
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  #- echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/$(uname -n) $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu mantic stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # install kubectl, kind for arm64 arch
  # config metabl-lb with layer2 https://kind.sigs.k8s.io/docs/user/loadbalancer/
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl" && install kubectl /usr/local/bin 
  - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-arm64 && install kind /usr/local/bin
  - mkdir -p /etc/kind
  - kind create cluster --name basic --config /etc/kind/2nodes-basic.yaml
  - kind get kubeconfig --name basic > /etc/kind/kubeconfig-basic
  - |
    kubectl get configmap kube-proxy -n kube-system -o yaml | \
    sed -e "s/strictARP: false/strictARP: true/" | \
    kubectl apply -f - -n kube-system
  - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
  - kubectl wait -n metallb-system --for=condition=ready pod -l app=metallb --timeout=90s
  - kubectl apply -f /etc/kind/metallb-config.yaml

# power_state:
#   mode: reboot
#   message: Restarting after installing docker & docker-compose

final_message: "The system is finally up, after $UPTIME seconds"